spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.189.138:3306/jwt?characterEncoding=utf-8&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.189.138
    port: 6379